### ISSUE TITLE
Unable to get authorisation code  programmatically 

### ISSUE THREAD

**Issue by durganath123** [Porter97/Python-Medium#5]
after getting  authorization url -

response = requests.get(auth_url,  headers={'Authorization': 'access_token xxx'})
i am getting 400 error..
 
if i am accessing auth_url  browser based by passing  login credential, i am able to get auth code. but i want withing the script.
pls  suggest me how  to overcome this problem and how can i use access_token provided in medium settings (integration tokens)

**Comment by Porter97** [comment]
The method your using seems to be directly trying to access the Medium API itself.

This library functions as an (unofficial!) wrapper around that API. The documentation in the readme can give you some guidance on how to use it. 

If you're having other issues towards interacting with the Medium API in methods not used in this library please direct them to Medium directly.
